# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  scheduler_config = debug
  tests_config = debug

else ifeq ($(config),release)
  scheduler_config = release
  tests_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := scheduler tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

scheduler:
ifneq (,$(scheduler_config))
	@echo "==== Building scheduler ($(scheduler_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(scheduler_config)
endif

tests:
ifneq (,$(tests_config))
	@echo "==== Building tests ($(tests_config)) ===="
	@${MAKE} --no-print-directory -C tests -f Makefile config=$(tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean
	@${MAKE} --no-print-directory -C tests -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   scheduler"
	@echo "   tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"